### ISSUE TITLE
USER STORY: Remove users from runners list

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/loverunning_modern#3]
As a **Website admin** I can **remove users** so that **I can avoid bots and eliminate users with unwanted behaviour**

# Acceptance Criteria
- Acceptance Criteria 1: Grant access to the website database
- Acceptance Criteria 2: create a database including all users

# Tasks
- [ ] Create an SQL database
- [ ] Grant access to the database only to the website owner and to developers 
- [ ] Create a GUI and a command line to manage the user list
