### ISSUE TITLE
USER STORY: Get weather condition 

### ISSUE THREAD

**Issue by AngeloGaeta1990** [AngeloGaeta1990/loverunning_modern#4]
As a **Website admin** I can **add info on the weather and on how to dress** so that **runners come prepared to trails**

# Acceptance Criteria
- Acceptance Criteria 1: Once the trail has been selected the weather is displayed automatically
- Acceptance Criteria 2: Website admin can give tips on how to dress for the trail

# Tasks
- [ ] Reach out to the weather website API to automatically display the weather at that time and the temperature
- [ ] Create HTML and CSS code to include a section where to display weather and website admin comments 
- [ ] Grant only to website admin access to weather sections to add advice on how to dress
